hooks:
  post-start:
    - exec: |
        if [ ! -f /var/www/html/.e2e_cloned ]; then
          git clone git@gitlab.vcat.de:vcat/e2e-testing.git /var/www/html/e2e-testing && \
          touch /var/www/html/.e2e_cloned
        fi
