# config.e2e-testing.yaml
hooks:
  pre-start:
    - exec-host: |
        if [ ! -f ${DDEV_APPROOT}/.e2e_cloned ]; then
          git clone git@gitlab.vcat.de:vcat/e2e-testing.git ${DDEV_APPROOT}/e2e-testing && \
          touch ${DDEV_APPROOT}/.e2e_cloned
        fi

